version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    expose:
      - "8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    expose:
      - "3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./frontend/.env
    command: ["pnpm", "run", "start"]
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
