"""refin Group id to primary

Revision ID: 5c7c5f0eee05
Revises: 
Create Date: 2025-03-29 01:58:56.014159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5c7c5f0eee05'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'start_time',
               existing_type=mysql.TIME(),
               nullable=False)
    op.alter_column('events', 'end_time',
               existing_type=mysql.TIME(),
               nullable=False)
    op.create_foreign_key(None, 'events', 'admins', ['admin_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'events', 'groups', ['group_id'], ['id'], ondelete='SET NULL')
    op.alter_column('groups', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('groups', 'admin_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'groups', 'admins', ['admin_id'], ['id'], ondelete='CASCADE')
    op.add_column('members', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.add_column('members', sa.Column('event_id', sa.String(length=36), nullable=True))
    op.alter_column('members', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_foreign_key(None, 'members', 'admins', ['admin_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'members', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.alter_column('permissions', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('fk_permissions_parent_id', table_name='permissions')
    op.drop_index('name', table_name='permissions')
    op.create_foreign_key(None, 'permissions', 'permissions', ['parent_id'], ['id'])
    op.alter_column('role_permissions', 'permission_id',
               existing_type=mysql.BIGINT(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.drop_constraint('role_permissions_ibfk_2', 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tickets', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('votes', 'candidate',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('votes', 'candidate',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('tickets', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key('role_permissions_ibfk_2', 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.alter_column('role_permissions', 'permission_id',
               existing_type=sa.String(length=36),
               type_=mysql.BIGINT(),
               existing_nullable=True)
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.create_index('name', 'permissions', ['name'], unique=True)
    op.create_index('fk_permissions_parent_id', 'permissions', ['parent_id'], unique=False)
    op.alter_column('permissions', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.alter_column('members', 'id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('members', 'event_id')
    op.drop_column('members', 'admin_id')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.alter_column('groups', 'admin_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('groups', 'id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.alter_column('events', 'end_time',
               existing_type=mysql.TIME(),
               nullable=True)
    op.alter_column('events', 'start_time',
               existing_type=mysql.TIME(),
               nullable=True)
    # ### end Alembic commands ###
