"""Update permission and role_ids to Integer

Revision ID: b0544686b385
Revises: 7f60247036e1
Create Date: 2025-04-03 22:34:22.174789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b0544686b385'
down_revision: Union[str, None] = '7f60247036e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fk_admins_role_id', table_name='admins')
    op.create_foreign_key(None, 'admins', 'roles', ['role_id'], ['id'])
    op.alter_column('permissions', 'parent_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'permissions', 'permissions', ['parent_id'], ['id'])
    op.alter_column('role_permissions', 'role_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.alter_column('role_permissions', 'role_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.alter_column('permissions', 'parent_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.create_index('fk_admins_role_id', 'admins', ['role_id'], unique=False)
    # ### end Alembic commands ###
