name: Deploy Docker Compose Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

   
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest
        

      - name: Deploy to Server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /tmp/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd ~/vote
            git pull

            # Stop and remove existing containers to free up memory
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker-compose down

            # Pull latest images
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker-compose pull

            # Rebuild and start containers with updated images
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker-compose up -d --build

            # Clean up unused images, build cache, and volumes to reclaim resources
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker image prune -f
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker builder prune --all -f
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker volume prune -f
          EOF
